language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
addons:
  apt:
    packages:
      - xserver-xephyr
jobs:
  include:
  - python: 3.9
    env: TOXENV=lint
install:
  - pip install tox-travis codecov
script:
  - tox
after_success:
  - codecov
